# Generated by Django 3.0.2 on 2020-03-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduardoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='seller',
        ),
    ]
