# Generated by Django 3.0.2 on 2020-04-07 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduardoApp', '0007_auto_20200317_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('articles', models.ManyToManyField(to='eduardoApp.OrderArticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduardoApp.User')),
            ],
        ),
    ]
