# Generated by Django 3.0.2 on 2020-04-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduardoApp', '0008_auto_20200407_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderarticle',
            name='article',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='eduardoApp.Article'),
            preserve_default=False,
        ),
    ]
