# Generated by Django 3.0.2 on 2020-04-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduardoApp', '0012_auto_20200407_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_name',
            new_name='name',
        ),
    ]
