# Generated by Django 3.0.2 on 2020-04-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduardoApp', '0013_auto_20200407_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='article_name',
        ),
    ]
