# Generated by Django 3.0.2 on 2020-04-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduardoApp', '0018_auto_20200410_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='availlable',
            field=models.BooleanField(default=True),
        ),
    ]
