# Generated by Django 3.0.4 on 2020-04-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduardoApp', '0023_auto_20200413_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
