# Generated by Django 3.0.2 on 2020-04-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduardoApp', '0026_auto_20200413_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='category'),
            preserve_default=False,
        ),
    ]
